
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MusicXML;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Scanner;
import java.io.IOException;
import java.io.*;
import java.io.File;
import java.awt.*;
import javax.swing.*;

//Not all of the above are needed, they are there just in case.

public class ConsoleTesting {
	
	public static void main (String[] args) throws Exception{
		
		File file = new File("tab1.txt");
		FileScanner readFile = new FileScanner(file);
		

		ArrayList <String[]> staffs = readFile.getStaffs();
		Keys keys = new Keys(staffs.get(0));

		
		for(int i = 0; i < staffs.size(); i++) {
			for(int j = 0; j < 6; j++) {
				System.out.println(staffs.get(i)[j]);
			}
			System.out.println();
		}
		
		Measures measures = new Measures(staffs.get(0));
		ArrayList<String[]> allMeasures = measures.getMeasures();
		
		for(int i = 0; i < allMeasures.size(); i++) {
			for(int j = 0; j < 6; j++) {
				System.out.println(allMeasures.get(i)[j]);
			}
			System.out.println();
		}
	}
}
