/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MusicXML;

public class Library {
    public boolean someLibraryMethod() {
    	int a = 0;
    	a = 100;
        return true;
    }
}
